paths:
  roms: roms
  models: working/models
  recordings: working/recordings
  cache: working/cache
  database: working/database.json

training:
  game: Airstriker-Genesis-v0
  savestate: Level1
  fingerprint: null

laya:
  checkpoint: convaiinnovations/laya

log_level: INFO

upload:
  url: https://speedlab.datenwissenschaften.com/api
  api_key: null

ui:
  enable: true
  host: 127.0.0.1
  port: 18080
  max_episodes: 1000
