paths:
  roms: roms
  models: working/models
  recordings: working/recordings
  cache: working/cache

training:
  game: Airstriker-Genesis-v0
  fingerprint: null
  savestate: null
  num_envs: auto

log_level: INFO

upload:
  url: https://speedlab.datenwissenschaften.com/api
  api_key: null

ui:
  enable: true
  host: 127.0.0.1
  port: 18080
  max_episodes: 1000
  redis_url: redis://127.0.0.1:6379/0
  history_key_prefix: datenwissenschaften:history
